version: '3'

services:
  db:
    image: mariadb:10.4
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql-dump/:/docker-entrypoint-initdb.d
    environment:
       MYSQL_DATABASE: 'test'
       MYSQL_USER: 'test'
       MYSQL_PASSWORD: 'test'
       MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - "3305:3306"
  web:
    environment:
      - IS_PRODUCTION=1
      - PYTHONUNBUFFERED=1
    build: .
    command: sh -c "python3 manage.py migrate &&  python3 manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"
    depends_on:
      - db